from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

MODEL_DIR = PROJECT_ROOT / "ssdlite_mobilenet_v2_coco_2018_05_09"
DATA_DIR = PROJECT_ROOT / "data"
VIDEO_DIR = PROJECT_ROOT / "road_traffic_videos"
ROI_CONFIGURATION_DIR = PROJECT_ROOT / "roi_configuration_files"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "database_detected_vehicles_images"
MODEL_NAME = "ssdlite_mobilenet_v2_coco_2018_05_09"
MODEL_FILE = MODEL_NAME + ".tar.gz"
PATH_TO_CKPT = MODEL_DIR / "frozen_inference_graph.pb"
PATH_TO_LABELS = DATA_DIR / "mscoco_label_map.pbtxt"
NUM_CLASSES = 90

INTEREST_AREA_X_START = 300
INTEREST_AREA_Y_START = 420
INTEREST_AREA_X_END = 1700
INTEREST_AREA_Y_END = 1060

SPEED_LIMIT = 30
PIXEL_TO_REAL_LENGTH = 0.02
PIXEL_HEIGHT_COMPENSATE = 0.0001

TRAFFIC_LIGHT_POS_TOP = 124
TRAFFIC_LIGHT_POS_BOTTOM = 144
TRAFFIC_LIGHT_POS_LEFT = 890
TRAFFIC_LIGHT_POS_RIGHT = 920

LINE_CROSSING_DETECTION_INTERVAL_IN_EACH_LANE = 6

SPEED_DETECTION_POSITION_LANE_TOP = 670
SPEED_DETECTION_POSITION_LANE_BOTTOM = 740
LEFT_SPEED_DETECTION_POSITION_LANE_FIRST = 450
RIGHT_SPEED_DETECTION_POSITION_LANE_FIRST = 800
LEFT_SPEED_DETECTION_POSITION_LANE_SECOND = 850
RIGHT_SPEED_DETECTION_POSITION_LANE_SECOND = 1200
LEFT_SPEED_DETECTION_POSITION_LANE_THIRD = 1250
RIGHT_SPEED_DETECTION_POSITION_LANE_THIRD = 1600

IS_LANE_FIRST_AVAILABLE = True
IS_LANE_SECOND_AVAILABLE = True
IS_LANE_THIRD_AVAILABLE = True

DETECTED_LIGHT_COLOR = "green"

VIDEO_FILE_NAME = "video-01"
